### ISSUE TITLE
How to handle deployment actions and ignored files

### ISSUE THREAD

**Issue by mike-diff** [3daddict/webpack-shopify-cli#22]
Need a way to manage and maintain ignored files in github actions so each deployment does not reset Shopify 2.0 templates.
- .github/staging.yml
- .github/production.yml
New templates need to be added the first time and then ignored...
Also looking for better alternatives?

```yml
  deploy_to_staging_theme:
    runs-on: ubuntu-latest
    needs: build_and_install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist

      - uses: discolabs/deploy-shopify-theme-action@v1
        with:
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_ACCESS_TOKEN }}
          publlished_theme_id: ${{ secrets.SHOP_THEME_ID }}
          path: 'dist'
#           additional_args: '--ignored-file=config/settings_data.json'
```
